// ═══════════════════════════════════════════════════════════════════════════
// ETERNAL PATH - Europa-Park Länder & Themenbereiche
// Basierend auf den echten Themenbereichen des Europa-Parks
// ═══════════════════════════════════════════════════════════════════════════

// Länder-Konfiguration mit Farben und Icons
export const COUNTRIES = {
  deutschland: {
    id: 'deutschland',
    name: 'Deutschland',
    flag: '🇩🇪',
    colors: ['#000000', '#DD0000', '#FFCC00'],
    primaryColor: '#DD0000',
    accentColor: '#FFCC00',
    bgGradient: ['#1a1a1a', '#DD0000'],
    icon: 'beer',
    questTypes: ['exploration', 'collection'],
    bonusMultiplier: 1.5,
  },
  frankreich: {
    id: 'frankreich',
    name: 'Frankreich',
    flag: '🇫🇷',
    colors: ['#002395', '#FFFFFF', '#ED2939'],
    primaryColor: '#002395',
    accentColor: '#ED2939',
    bgGradient: ['#002395', '#ED2939'],
    icon: 'wine',
    questTypes: ['social', 'networking'],
    bonusMultiplier: 1.3,
  },
  spanien: {
    id: 'spanien',
    name: 'Spanien',
    flag: '🇪🇸',
    colors: ['#AA151B', '#F1BF00'],
    primaryColor: '#AA151B',
    accentColor: '#F1BF00',
    bgGradient: ['#AA151B', '#F1BF00'],
    icon: 'sunny',
    questTypes: ['adventure', 'thrill'],
    bonusMultiplier: 1.4,
  },
  holland: {
    id: 'holland',
    name: 'Holland',
    flag: '🇳🇱',
    colors: ['#AE1C28', '#FFFFFF', '#21468B'],
    primaryColor: '#FF6B00',
    accentColor: '#21468B',
    bgGradient: ['#FF6B00', '#21468B'],
    icon: 'flower',
    questTypes: ['family', 'relaxation'],
    bonusMultiplier: 1.2,
  },
  italien: {
    id: 'italien',
    name: 'Italien',
    flag: '🇮🇹',
    colors: ['#009246', '#FFFFFF', '#CE2B37'],
    primaryColor: '#009246',
    accentColor: '#CE2B37',
    bgGradient: ['#009246', '#CE2B37'],
    icon: 'pizza',
    questTypes: ['culinary', 'culture'],
    bonusMultiplier: 1.3,
  },
  griechenland: {
    id: 'griechenland',
    name: 'Griechenland',
    flag: '🇬🇷',
    colors: ['#0D5EAF', '#FFFFFF'],
    primaryColor: '#0D5EAF',
    accentColor: '#FFFFFF',
    bgGradient: ['#0D5EAF', '#1a3a5c'],
    icon: 'sunny',
    questTypes: ['mythology', 'adventure'],
    bonusMultiplier: 1.4,
  },
  oesterreich: {
    id: 'oesterreich',
    name: 'Österreich',
    flag: '🇦🇹',
    colors: ['#ED2939', '#FFFFFF'],
    primaryColor: '#ED2939',
    accentColor: '#FFFFFF',
    bgGradient: ['#ED2939', '#8B0000'],
    icon: 'musical-notes',
    questTypes: ['music', 'tradition'],
    bonusMultiplier: 1.2,
  },
  schweiz: {
    id: 'schweiz',
    name: 'Schweiz',
    flag: '🇨🇭',
    colors: ['#FF0000', '#FFFFFF'],
    primaryColor: '#FF0000',
    accentColor: '#FFFFFF',
    bgGradient: ['#FF0000', '#8B0000'],
    icon: 'snow',
    questTypes: ['precision', 'quality'],
    bonusMultiplier: 1.5,
  },
  england: {
    id: 'england',
    name: 'England',
    flag: '🇬🇧',
    colors: ['#012169', '#FFFFFF', '#C8102E'],
    primaryColor: '#012169',
    accentColor: '#C8102E',
    bgGradient: ['#012169', '#C8102E'],
    icon: 'cafe',
    questTypes: ['networking', 'mystery'],
    bonusMultiplier: 1.3,
  },
  skandinavien: {
    id: 'skandinavien',
    name: 'Skandinavien',
    flag: '🇸🇪',
    colors: ['#006AA7', '#FECC00'],
    primaryColor: '#006AA7',
    accentColor: '#FECC00',
    bgGradient: ['#006AA7', '#004F7F'],
    icon: 'snow',
    questTypes: ['nature', 'viking'],
    bonusMultiplier: 1.4,
  },
  russland: {
    id: 'russland',
    name: 'Russland',
    flag: '🇷🇺',
    colors: ['#FFFFFF', '#0039A6', '#D52B1E'],
    primaryColor: '#0039A6',
    accentColor: '#D52B1E',
    bgGradient: ['#0039A6', '#D52B1E'],
    icon: 'snow',
    questTypes: ['adventure', 'thrill'],
    bonusMultiplier: 1.5,
  },
  portugal: {
    id: 'portugal',
    name: 'Portugal',
    flag: '🇵🇹',
    colors: ['#006600', '#FF0000'],
    primaryColor: '#006600',
    accentColor: '#FF0000',
    bgGradient: ['#006600', '#004400'],
    icon: 'boat',
    questTypes: ['exploration', 'discovery'],
    bonusMultiplier: 1.3,
  },
  island: {
    id: 'island',
    name: 'Island',
    flag: '🇮🇸',
    colors: ['#003897', '#FFFFFF', '#D72828'],
    primaryColor: '#003897',
    accentColor: '#D72828',
    bgGradient: ['#003897', '#001a4d'],
    icon: 'water',
    questTypes: ['nature', 'adventure'],
    bonusMultiplier: 1.6,
  },
  irland: {
    id: 'irland',
    name: 'Irland',
    flag: '🇮🇪',
    colors: ['#169B62', '#FFFFFF', '#FF883E'],
    primaryColor: '#169B62',
    accentColor: '#FF883E',
    bgGradient: ['#169B62', '#0d5c3a'],
    icon: 'leaf',
    questTypes: ['luck', 'social'],
    bonusMultiplier: 1.3,
  },
  luxemburg: {
    id: 'luxemburg',
    name: 'Luxemburg',
    flag: '🇱🇺',
    colors: ['#ED2939', '#FFFFFF', '#00A3E0'],
    primaryColor: '#00A3E0',
    accentColor: '#ED2939',
    bgGradient: ['#00A3E0', '#006699'],
    icon: 'business',
    questTypes: ['networking', 'business'],
    bonusMultiplier: 1.4,
  },
};

export const COUNTRY_LIST = Object.values(COUNTRIES);

// Länder nach Quest-Typ gruppieren
export const getCountriesByQuestType = (questType) => {
  return COUNTRY_LIST.filter(country => 
    country.questTypes.includes(questType)
  );
};

// Bonus-Multiplikator für ein Land bekommen
export const getCountryBonus = (countryId) => {
  return COUNTRIES[countryId]?.bonusMultiplier || 1.0;
};

export default COUNTRIES;
